# Generated by Django 4.1.4 on 2022-12-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit_basic",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("PC", "Piece"),
                            ("PKT", "Packet"),
                            ("MTR", "Meter"),
                            ("UNIT", "Unit"),
                        ],
                        default="UNIT",
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Rate of the item as per the basic unit",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="customer.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
            },
        ),
    ]
